services:
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    volumes:
      - ${PWD}/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ${PWD}/builds:/builds
    restart: always