concurrent = 4
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[[runners]]
  name = "docker-runner-local.3"
  url = "https://gitlab.com/"
  token = "glrt-rCrK9KYQam1upsjq2sPu"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.docker]
    tls_verify = false
    image = "alpine"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_flush = false
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

